project:
  name: wipedish_sensor_only
  output_dir: logs

runtime:
  duration_sec: 10
  snapshot_timeout_sec: 10
  expected_fps: 24
  sync_slop: 0.4
  obs_buffer_size: 1024

robot:
  backend: forcemimic_rizon
  robot_id: Rizon4s-063586
  tool_name: hapticexoteleop
  gripper_id: 1659f0e0dde0
  gripper_name: Xense
  gripper_block: false
  arm: left
  bimanual: false
  read_fps: 90

data_processing:
  mode: single_arm_one_wrist_camera
  image_resize_shape: [320, 240]
  use_6d_rotation: true
  debug: false

devices:
  robot:
    enabled: true
    fps: ${robot.read_fps}
  realsense:
    enabled: true
    cameras:
      - camera_serial_number: "260322274925"
        camera_name: left_wrist_camera
        rgb_resolution: [640, 480]
        fps: 30
        stream_fps: 30
        warmup_frames: 30

observation:
  history_size: 2
  required_keys:
    - left_wrist_img
    - left_robot_tcp_pose
    - left_robot_gripper_width
    - left_robot_tcp_wrench

collection:
  save_snapshot_pickle: true
  save_stream_numpy: true
  save_stream_pickle: true

model:
  # 可通过 validate_offline_control.py 的命令行参数覆盖。
  checkpoint_path: ../wipedish_7_17/LDP/checkpoints/latest.ckpt
  at_checkpoint_path: ../wipedish_7_17/AT/checkpoints/latest.ckpt
  device: cuda:0
  use_ema: auto
  num_inference_steps: 8
  dataset_obs_temporal_downsample_ratio: 2
  decoder_horizon: 32
  seed: 42
  print_steps: 5
