project:
  name: wipedish_sensor_only
  output_dir: logs

runtime:
  duration_sec: 10
  snapshot_timeout_sec: 10
  expected_fps: 24
  sync_slop: 0.4
  obs_buffer_size: 1024

robot:
  backend: forcemimic_rizon
  robot_id: Rizon4s-063586
  tool_name: hapticexoteleop
  gripper_id: 1659f0e0dde0
  gripper_name: Xense
  gripper_block: false
  arm: left
  bimanual: false
  read_fps: 90

data_processing:
  mode: single_arm_two_realsense_two_tactile
  image_resize_shape: [320, 240]
  use_6d_rotation: true
  marker_dimension: 2
  debug: false

devices:
  robot:
    enabled: true
    fps: ${robot.read_fps}
  realsense:
    enabled: true
    cameras:
      - camera_serial_number: "260322274925"
        camera_name: D405
        rgb_resolution: [640, 480]
        fps: 30
        stream_fps: 30
        warmup_frames: 30
  xense:
    enabled: true
    sensors:
      - sensor_name: left_gripper_camera_1
        serial_number: OG001452
        mac_address: 1659f0e0dde0
        cam_id: null
        config_path: null
        use_gpu: true
        fps: 24
        calibrate_on_start: true
        read_rectify: true
        read_marker2d: true
        read_force_resultant: true
        read_timestamp: true

observation:
  required_keys:
    - timestamp
    - agentview_image
    - left_gripper1_img
    - left_gripper1_marker_offset
    - left_gripper1_force_resultant
    - left_robot_tcp_pose
    - left_robot_gripper_width
    - left_robot_tcp_wrench

collection:
  save_snapshot_pickle: true
  save_stream_numpy: true
  save_stream_pickle: true
