sensors:
  subscribe_topics:
    - name: /external_camera/color/image_raw
      type: sensor_msgs/msg/Image
    - name: /left_wrist_camera/color/image_raw
      type: sensor_msgs/msg/Image
    - name: /left_gripper_camera_1/color/image_raw
      type: sensor_msgs/msg/Image
    - name: /left_gripper_camera_1/marker_offset/information
      type: sensor_msgs/msg/PointCloud2
    - name: /left_gripper_camera_1/force_resultant
      type: geometry_msgs/msg/WrenchStamped
    - name: /left_tcp_pose
      type: geometry_msgs/msg/PoseStamped
    - name: /left_gripper_state
      type: sensor_msgs/msg/JointState
    - name: /left_tcp_vel
      type: geometry_msgs/msg/TwistStamped
    - name: /left_tcp_wrench
      type: geometry_msgs/msg/WrenchStamped
  required_observation_keys:
    - timestamp
    - left_robot_tcp_pose
    - left_robot_gripper_width
    - left_robot_tcp_wrench
  expected_ros_topics:
    - /external_camera/color/image_raw
    - /left_wrist_camera/color/image_raw
    - /left_gripper_camera_1/color/image_raw
    - /left_gripper_camera_1/marker_offset/information
    - /left_gripper_camera_1/force_resultant
    - /left_tcp_pose
    - /left_gripper_state
    - /left_tcp_vel
    - /left_tcp_wrench

data_processing:
  mode: single_arm_two_realsense_two_tactile
  image_resize_shape: [320, 240]
  use_6d_rotation: true
  marker_dimension: 2
  debug: false
